### PR TITLE
Add `deploy.yml` to deploy docker container on docker hub

### PR DESCRIPTION
**Pull request by harshsharma2002**
- the file builds and deploys the image and then push it to docker hub.
- requires 2 github secret token that is `DOCKER_USERNAME` and `DOCKER_PASSWORD` to be set to access the docker hub.

### CODE REVIEW

**Comment by harshsharma2002** [comment]
The deployment of the image to docker hub is working fine, but to deploy it to render and fly.io, both require paid accounts so i am not able to test them on those, please help me with the next steps.
image
image

**Comment by anipnwr7777** [comment]
Hey, I do see a free tier for both the services. Sharing for you reference.
https://fly.io/docs/about/pricing/#new-customers
https://render.com/pricing

**Comment by harshsharma2002** [comment]
Hey, @anipnwr7777 the issue i am facing is that we need to have a app setup first on the fly.io account only then we can use the `fly.toml` and deploy to that app but in the free version of fly.io we cannot create a app.

please guide me for the next steps.
image
image

i have the workflow and `fly.toml` ready but i am unable to test it.

**Comment by anipnwr7777** [comment]
I don't think there is a way out if setting this up requires payment. Let me think what i can do about it.

**Comment by anipnwr7777** [comment]
@harshsharma2002 I will be taking this forward. Thanks for your time and effort.

**Pull request closed without merging**
